---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  ENV: production
  PORT: 8080

 # --------------------------------------------------------------------------

 # through command

 # kubectl create configmap my-config-map --from-literal=ENV=production --from-literal=LOG_LEVEL=debug
