---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: mycont
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "10Mi"
            limits:
              cpu: "300m"
              memory: "20Mi"
          envFrom:
            - configMapRef:
                name: my-config-map
            - secretRef:
                name: my-secret












                
