---
apiVersion: v1
kind: Service
metadata:
  name: myservice-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 80
      
# stableIP + nodeport + DNS name


/*
----------------------------------------------------------------------------------------------------------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: myservice-nodeport
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 80         # Cluster port
      targetPort: 80   # Pod container port
      nodePort: 30007  # Static port on each Node
      
# stableIP + nodeport

-----------------------------------------------------------------------------------------------------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: myservice-clusterip
spec:
  type: ClusterIP
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 80

  # stableIP


 */     

      
